relative_url/relative_app/urls.py
from django.urls import path
from relative_app import views

app_name = 'relative_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('relative', views.relative, name='relative'),
    path('other_page', views.other_page, name='other_page')
]

relative_url/relative_url/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('relative_app.urls')),
]

relative_url/relative_app/models.py
from django.db import models

# Create your models here.

relative_url/relative_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'index.html')


def relative(request):
    con_dict = {'text': 'hello world'}
    return render(request, 'relative.html', con_dict)


def other_page(request):
    return render(request, 'other_page.html')

relative_url/relative_app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>BASE</title>
        <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'relative_app:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'relative_app:relative' %}">relative</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'relative_app:other_page' %}">other_page</a>
      </li>
    </ul>
  </div>
</nav>

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            {% block body_block %}

            {% endblock %}
        </div>
    </div>
    </body>
</html>

relative_url/relative_app/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}

    {% block body_block %}

        <h1>Welcome to index page</h1>

    {% endblock %}

relative_url/relative_app/templates/other_page.html
<!DOCTYPE html>
{% extends "base.html" %}

    {% block body_block %}

        <h1>This is Other page</h1>

    {% endblock %}

relative_url/relative_app/templates/relative.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load extra_tags %}

    {% block body_block %}
    <h1>This is relative home page</h1>
    <h1>{{ text|upper }}</h1>
    <h1>{{ text|cutWord:'hello' }}</h1>
    <p></p>
    <a href="{% url 'relative_app:other_page' %}">Other page</a>

    {% endblock %}