classBasedViews/classBasedViews/urls.py
from django.contrib import admin
from django.urls import path, include
from class_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Indexview.as_view(), name='index'),
    path('class_app/', include('class_app.urls'))
    #path('', views.index, name='index'),
]

classBasedViews/class_app/urls.py
from django.urls import path, include
from class_app import views

app_name = 'class_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail')
]

classBasedViews/class_app/models.py
from django.db import models

# Create your models here.


class School(models.Model):

    name = models.CharField(max_length=256)
    principle = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Student(models.Model):

    first_name = models.CharField(max_length=256)
    age = models.IntegerField()
    school = models.ForeignKey('School', on_delete=models.CASCADE, related_name='students')

    def __str__(self):
        return self.first_name

classBasedViews/class_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
from . import models
# Create your views here.


class Indexview(TemplateView):

    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        #context = super().get_context_data(**kwargs)
        context = TemplateView.get_context_data(self, **kwargs)
        context['ineject'] = "Hey I'm context"
        return context


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'schools_details'
    model = models.School

    Template_name = r'class_app/school_detail.html'

classBasedViews/class_app/templates/class_app/class_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'class_app:list' %}">Schools</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>

    </ul>
  </div>
</nav>

    <div class="container">

            {% block body_block %}


            {% endblock %}

</div>



    </body>
</html>

classBasedViews/class_app/templates/class_app/school_detail.html
{% extends 'class_app/class_app_base.html' %}

{% block body_block %}

    <div class="jumbotron">
        <h1>Welcome to school detail page</h1>
        <h2>School details:</h2>

        <p>Name : {{ schools_details.name }}</p>
        <p>Principle: {{ schools_details.principle }}</p>
        <p>Location: {{ schools_details.location }}</p>

        <h3>Students : </h3>

        {% for student in schools_details.students.all %}
        <p>{{ student.first_name }} who is {{ student.age }} old</p>
        {% endfor%}
    </div>

{% endblock %}

classBasedViews/class_app/templates/class_app/school_list.html
{% extends 'class_app/class_app_base.html' %}

{% block body_block %}

    <h1>Welcome to list of all schools</h1>

    <ol>
        {% for school in schools %}
        <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
        {% endfor %}
    </ol>

{% endblock %}

classBasedViews/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'class_app:list' %}">Schools</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>

    </ul>
  </div>
</nav>

    <div class="container">

            {% block body_block %}


            {% endblock %}



        </div>



    </body>
</html>

classBasedViews/templates/index.html
{% extends "base.html" %}

{% block body_block %}


    <div class="jumbotron">
        <h1>Home Page</h1>
    </div>




{% endblock %}